# Generated by Django 5.2.4 on 2025-07-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('classe_faq', models.CharField(choices=[('cooperados', 'Cooperados'), ('parceiros', 'Parceiros'), ('fornecedores', 'Fornecedores')], default='cooperados', max_length=20)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conteudos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.TextField()),
                ('isativo', models.BooleanField(default=True, help_text='Marcar como FAQ ativo')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('num_views', models.PositiveIntegerField(default=0, help_text='Número de visualizações')),
                ('num_likes', models.PositiveIntegerField(default=0, help_text='Número de curtidas')),
                ('num_unlikes', models.PositiveIntegerField(default=0, help_text='Número de descurtidas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
    ]
